version: "3"

services:
  backend:
    build: .
    command: bash run.sh
    volumes:
      - .:/app
    ports:
      - "7755:7755"
    restart: always

  test:
    build: .
    command: bash test.sh
    volumes:
      - .:/app

  coverage:
    build: .
    command: bash coverage.sh
    volumes:
      - .:/app
